INSERT INTO crime_heads (name, category) VALUES 
('Murder', 'Heinous'),
('Att. Murder', 'Heinous'),
('Cul. Homicide', 'Heinous'),
('Rape', 'Heinous'),
('Minor', 'Heinous'),
('Major', 'Heinous'),
('Dacoity', 'Property'),
('Prof.', 'Property'),
('Technical.', 'Property'),
('Pre. Of Dacoity', 'Property'),
('Robbery', 'Property'),
('Chain snatching', 'Property'),
('HBT', 'Property'),
('Day', 'Property'),
('Night', 'Property'),
('Theft', 'Property'),
('Two Wheeler', 'Theft'),
('3&4 Wheeler, Heavy Vehicle', 'Theft'),
('Other', 'Theft'),
('Riot', 'Law & Order'),
('Criminal Breach Of Trust', 'Property'),
('Cheating', 'Property'),
('Kidnapping', 'Heinous'),
('House Trespass', 'Property'),
('Mischief', 'Property'),
('Hurt', 'Body'),
('Assault on Gov. Servant', 'System'),
('Police', 'System'),
('Other Department', 'System'),
('Molestation', 'Heinous'),
('Abetment Suicide', 'Heinous'),
('Total 304 A IPC.', 'Accident'),
('MV Fatal Accident', 'Accident'),
('Death Caused due to Negligence', 'Accident'),
('Other 1 to 5', 'Other');
